name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, v6]

jobs:
  lint:
    name: JSDoc

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci --ignore-scripts
    - run: npm run docs
